name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
        rust:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install YAJL
        run: sudo apt-get install -y libyajl-dev
        continue-on-error: true

      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          lfs: "true"
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Display Toolchain Information
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          ROOT_KEYSTORE=~/root_keystore.p12 cargo test --all

      - name: Build
        run: |
          cargo build --release
